<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VIImpact.Application\VIImpact.Application.csproj" />
    <ProjectReference Include="..\VIImpact.Domain\VIImpact.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource
      Include="Data\Seed\gta-events.json"
      LogicalName="VIImpact.Infrastructure.Data.Seed.gta-events.json" />
  </ItemGroup>

</Project>
